website/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       
                       url(r'^projects/(.+)/$', 'personal.views.project_details'),
                       url(r'^projects/$', 'personal.views.projects'),

                       url(r'^publications/(.+)/$', 'personal.views.publication_details'),
                       url(r'^publications/$', 'personal.views.publications'),

                       url(r'^experiments/(.+)/$', 'personal.views.experiment_details'),
                       url(r'^experiments/$', 'personal.views.experiments'),

                       url(r'^compositions/(.+)/$', 'personal.views.composition_details'),
                       url(r'^compositions/$', 'personal.views.compositions'),
                       
                       url(r'^performances/(.+)/$', 'personal.views.performance_details'),
                       url(r'^performances/$', 'personal.views.performances'),

                       url(r'^installations/(.+)/$', 'personal.views.installation_details'),
                       url(r'^installations/$', 'personal.views.installations'),
                       
                       
                       url(r'^music/$', 'personal.views.music'),

                       
                       url(r'^classes/$', 'personal.views.classes'),
                       url(r'^about/$', 'personal.views.about'),
                       url(r'^resume/$', 'personal.views.resume'),
                       url(r'^contact/$', 'personal.views.contact'),
                       url(r'^links/$', 'personal.views.links'),
                       
                       url(r'^$', 'personal.views.home'),
    

)

personal/models.py
from django.db import models

# Common Abstract Class

class GridList(models.Model):
    date = models.DateField()
    title = models.CharField(max_length=16)
    short = models.CharField(max_length=32,blank=True,null=True)
    source = models.URLField(max_length=64,blank=True,null=True)
    product = models.URLField(max_length=64,blank=True,null=True)
    description = models.CharField(max_length=256,blank=True,null=True)
    def __unicode__(self):
        return self.title

# Sections

class Project(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)
    performances = models.ManyToManyField('Performance')

class Performance(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)
    link = models.URLField()
    projects = models.ManyToManyField(Project,through=Project.performances.through)

class Installation(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)
    project = models.ForeignKey(Project)

class Composition(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)

class Experiment(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)

class Publication(GridList):
    gridlist_id = models.OneToOneField(GridList,parent_link=True)
    conference = models.CharField(max_length=128)
    project = models.ForeignKey(Project)

# Detail Field
class TextDetail(models.Model):
    item = models.ForeignKey(GridList)
    title = models.CharField(max_length=16)
    detail = models.CharField(max_length=1024)

# Resource helper classes

class Helper(models.Model):
    item = models.ForeignKey(GridList)
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=1024,blank=True,null=True)
    link = models.URLField(max_length=1024)
    def __unicode__(self):
        return self.title
    class Meta:
        abstract = True

class Link(Helper):
    pass

class Image(Helper):
    def __unicode__(self):
        return self.screenshot

class Video(Helper):
    def __unicode__(self):
        return self.project.title + ":" + self.title

class Category(Helper):
    pass

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>mayank | {% block title %}{{title}}{% endblock %}</title>
        
        <!-- Google Anaytics Code-->
        		<script type="text/javascript">
        		  var _gaq = _gaq || [];
        		  _gaq.push(['_setAccount', 'UA-33182197-1']);
        		  _gaq.push(['_trackPageview']);
        		  (function() {
        		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        		  })();
        		</script>
        <!-- END: Google Anaytics Code-->
        
        <!--CSS includes-->
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Raleway:100,300,500" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
        <!--JS includes-->
        <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
        <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
        
        {% block head %}{% endblock %}

        <!--custom CSS-->
        <link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css" />
        <!--custom JS-->
	</head>
	<body>
        <div class="container-narrow">
            <section>      
                {% if not request.GET.lightbox == "1" %}
                
                <script type="text/javascript">
                    $("body").attr('id','main');
                    // $(document).tooltip();
                	$(document).ready(function() {
                        $("#main-content").css("display", "none");
                        $("#main-content").fadeIn(1000);
                        
                    	$("a.fadeout").click(function(event){
                            if (!event.metaKey && !event.shiftKey) {   // allow open in new tab/window
                                event.preventDefault();
                        		linkLocation = this.href;
                        		$("#main-content").fadeOut(500, function() {
                        		window.location = linkLocation;
                                    }
                                );
                            }
                      });
                }); 
                </script>
                    <div class="masthead">
                        <ul class="nav nav-pills pull-right">                    
                            <li {% if title == "projects" %}class="active"{% endif %}><a href="/projects/" title="sufficiently finished" class="fadeout">Projects</a></li>
                            <li {% if title == "publications" %}class="active"{% endif %}><a href="/publications/" title="published research" class="fadeout">Publications</a></li>
                            <li {% if title == "experiments" %}class="active"{% endif %}><a href="/experiments/" title="doodlings in code" class="fadeout">Experiments</a></li>
                            <li {% if title == "performances" %}class="active"{% endif %}><a href="/performances/" title="with a public audience" class="fadeout">Performances</a></li>
                            <li {% if title == "compositions" %}class="active"{% endif %}><a href="/compositions/" title="primarily created on paper" class="fadeout">Compositions</a></li>
                            <li {% if title == "music" %}class="active"{% endif %}><a href="/music/" title="doodlings on guitar" class="fadeout">Recordings</a></li>
                        </ul>
                        <h1 class="muted"><a href="/">Mayank<br/>
                             Sanganeria</a></h1>
                    </div>
                <div id="main-content">
            {% else %}
                <div>
            {% endif %}
                {% block detail_content %}{% endblock %}                
                {% block content %}{% endblock %}
            </div>
            <div id="footer">
                <!-- © 2013 Mayank Sanganeria -->
            </div>
            </section>
        </div>
    </div>
   </body>
</html>

templates/base_details.html
{% extends "base.html" %}

{% block title %}{{item.title}}{% endblock %}

{% block detail_content %}
<div id="detail-content">
    <div class="row-fluid">
        <div class="span6">
            <div id="header-title" class="detail-heading">
                {{item.title}}
            </div>
        </div>
        <div class="span6">
            <div id="header-date" class="detail-item">
                {{item.date}}
            </div>
        </div>
    </div>

{% block video %} {% endblock video %}


{% if item.product %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            Product
        </div>
    </div>    
    
    <div class="span6">
        <div class="detail-item">
            <a href="{{item.product}}" target="blank">
                {{item.product}}
            </a>
        </div>
    </div>
</div>
{% endif %}

{% if item.source %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            Source
        </div>
    </div>    
    
    <div class="span6">
        <div class="detail-item">
            <a href="{{item.source}}" target="blank">
                {{item.source}}
            </a>
        </div>
    </div>
</div>
{% endif %}

{% if item.description %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            Description
        </div>
    </div>    
    
    <div class="span6">
        <div class="detail-item">
            {{item.description}}
        </div>
    </div>
</div>
{% endif %}



{% for detail in item.textdetail_set.all %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            {{detail.title}}
        </div>
    </div>    
    
    <div class="span6">
        <div class="detail-item">
        	{{detail.detail}}
        </div>
    </div>
</div>
{% endfor %}


{% block additional_content %} {% endblock %}

</div>
{% endblock %}

templates/classes.html
{% extends 'base.html' %}
{% block title %}Classes{% endblock %}

{% block content %}
Content goes here
{% endblock %}

templates/composition_details.html
{% extends 'base_details.html' %}

{% block additional_content %}

<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            audio
        </div>
    </div>        
    <div class="span6">
        <div class="detail-item">
            <audio controls>
              <source src="/static/compositions/{{item.title}}/rendition.mp3" type="audio/mpeg">
            Your browser does not support the audio element.
            </audio>
        </div>
    </div>        
</div>

<div class="row-fluid">
    <div class="span11">
        <img class="score" src="/static/compositions/{{item.title}}/score.png">
    </div>
</div>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}

{% block content %}

    <p>
        Mayank Sanganeria
    </p>
    <p>
        Center for Computer Research in Music and Acoustics</br>
        The Knoll!<br/>
        660 Lomita Drive<br/>
        Stanford University<br/>
        Stanford, CA 94305<br/>
        USA<br/>
    </p>
        
    <p>
        mayank@ccrma.stanford.edu
    </p>



{% endblock %}

templates/experiment_details.html
{% extends 'base_details.html' %}
{% block content %}
{% endblock %}

templates/grid.html
{% extends 'base.html' %}
{% load listutil %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static "css/jquery.fancybox.css" %}" type="text/css" media="screen" />
<script type="text/javascript" src="{% static "js/jquery.fancybox.pack.js" %}"></script>        
<script type="text/javascript" src="{% static "js/caman.full.min.js" %}"></script>        

<script type="text/javascript">
	$(document).ready(function() {
        $(".fancybox")
            .attr('rel', 'gallery')
            .fancybox({
                openEffect: 'elastic',
                closeEffect: 'elastic',
                openSpeed: 250,
                closepeed: 250,
                padding  : 0,
            });
            //light box code
        $("a.grid-item").click( function (event) {
            if (!event.metaKey && !event.shiftKey) {    //allow opening in new tab and window
               event.preventDefault();
                $('#'+this.name).click();
            }
            
            // Caman('.grid-image', function () {
            //   this.brightness(10);
            //   this.contrast(30);
            //   this.sepia(60);
            //   this.saturation(-30);
            //   this.render();
            // });
        });
            
});
</script>		
{% endblock %}

{% block content %}
{% for item in items %}
<a class="fancybox fancybox.iframe" href="/{{title}}/{{item.title}}/?lightbox=1" title="{{item.title}}" id="{{item.title|cut:' '}}"></a>
{% endfor %}

<div class="row-fluid">
    {% for item_list in items|partition_horizontal:"3" %}
        <div class="span4">
        {% for item in item_list %}
        <div class="grid-item">
                <div id="photo">
                    <a class="grid-item" href="/{{title}}/{{item.title}}/" name="{{item.title|cut:' '}}">
                    <div id="picture">
                        <div id="info">
                            <div id="holder">
                              <div id="grid-item-title">
                                  {{item.title}}
                              </div>
                              <div id="grid-item-short">
                                  {{item.short}}
                              </div>
                            </div>
                        </div>
                        <img src="/static/{{title}}/{{item.title}}/thumbnail.png" class="grid-image">
                    </div>
                    </a>
                </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/grid_django.html
{% extends 'base.html' %}
{% load listutil %}
{% load jsonify %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static "css/jquery.fancybox.css" %}" type="text/css" media="screen" />
<script type="text/javascript" src="{% static "js/jquery.fancybox.pack.js" %}"></script>        
<script type="text/javascript" src="{% static "js/caman.full.min.js" %}"></script>        

<script type="text/javascript">
    categories = $.parseJSON('{{categories|jsonify}}');
    items = $.parseJSON('{{items|jsonify}}');
	$(document).ready(function() {
        $(".fancybox")
            .attr('rel', 'gallery')
            .fancybox({
                openEffect: 'elastic',
                closeEffect: 'elastic',
                openSpeed: 250,
                closepeed: 250,
                padding  : 0,
            });
            //light box code
        $("a.grid-item").click( function (event) {
            if (!event.metaKey && !event.shiftKey) {    //allow opening in new tab and window
               event.preventDefault();
                $('#'+this.name).click();
            }
            
            // Caman('.grid-image', function () {
            //   this.brightness(10);
            //   this.contrast(30);
            //   this.sepia(60);
            //   this.saturation(-30);
            //   this.render();
            // });            
        });
            
});
</script>		
{% endblock %}

{% block content %}
{% for item in items %}
<a class="fancybox fancybox.iframe" href="/{{title}}/{{item.title}}/?lightbox=1" title="{{item.title}}" id="{{item.title|cut:' '}}"></a>
{% endfor %}

<div class="row-fluid">
    {% for item_list in items|partition_horizontal:"3" %}
        <div class="span4">
        {% for item in item_list %}
        <div class="grid-item">
                <div id="photo">
                    <a class="grid-item" href="/{{item.ClassType}}/{{item.title}}/" name="{{item.title|cut:' '}}">
                    <div id="picture">
                        <div id="info">
                            <div id="holder">
                              <div id="grid-item-title">
                                  {{item.title}}
                              </div>
                              <div id="grid-item-short">
                                  {{item.short}}
                              </div>
                            </div>
                        </div>
                        <img src="/static/{{item.ClassType}}/{{item.title}}/thumbnail.png" class="grid-image">
                    </div>
                    </a>
                </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}home{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span8 offset2">
        <div class="post">
            <h3>
                Intro
            </h3>
            <p>
                I'm an engineer and computer musician at <a href="http://ccrma.stanford.edu">CCRMA</a>, <a href="http://www.stanford.edu">Stanford</a>. Check out what I've been upto since coming here in September 2011
            </p>
            <h3>
                Current
            </h3>
            <p>
                Currently, I'm working on some Machine Learning through Andrew Ng's lecture videos and notes and hope to combine it with some spectral DSP for better pitch detection and source separation. This will be up in Experiments soon!
            </p>
            <h3>
                This Website
            </h3>
            <p>
                I built this website using Django, Twitter Bootstrap, jQuery and jQuery plugins. It has been tested and verified to work on Chrome 24, Safari 6 and Firefox 18. It uses CSS3 so older versions might not work as intended. t
            </p>
            <!-- <h3>
                <a href="/projects/">Projects</a>
            </h3>
            <p>
                Here you can find videos, descriptions, source codes for most of my projects. You can also check out the actual product if it's ready through the links here.
            </p>
            <h3>
                <a href="/experiments/">Experiments</a>
            </h3>
            <p>
                This is where I put up some of my code that is either in progress or in a very rudimentary state with lots of potential
            </p>
            <h3>
                <a href="/performances/">Performances</a>
            </h3>
            <p>
                This is where you can see video recordings of the performances I have done over the past year
            </p>
            <h3>
                <a href="/compositions/">Compositions</a>
            </h3>
            <p>
                This is where you can see and hear some of my compositions made for my Jazz Guitar lessons
            </p>
            <h3>
                <a href="/music/">Recordings</a>
            </h3>
            <p>
                These are some of the doodlings on guitar that I have made in the past few years. This section is a little sparse on new content because I keep injuring my wrists (twice in the last year) in bike accidents hich renders me unable to play for months
            </p> -->
            
            <h3>
                Contact
            </h3>
            <p>
                You can reach me through <a href="mailto:mayank@ccrma.stanford.edu" target="_blank">email</a>
            </p>            
        </div>
    </div>
    <div class="span2">
    </div>
</div>

{% endblock %}

templates/installation_details.html
{% extends 'base_details.html' %}
{% block content %}
	<p>	
		{{item.description}}
	</p>

{% endblock %}

templates/music.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="/static/css/sc-player-standard.css" type="text/css" />
{% endblock %}


{% block content %}
  <div class="row">
    <div class="span11">
        <div id="music-player">
            <a href="http://soundcloud.com/e7mac" class="sc-player">My tracks</a>
            <script type="text/javascript" src="/static/js/soundcloud.player.api.js"></script>
            <script type="text/javascript" src="/static/js/sc-player.js"></script>
        </div>
    </div>
</div>

{% endblock %}

templates/performance_details.html
{% extends 'base_details.html' %}
{% load listutil %}

{% block video %}
<div class="row-fluid">
    <div class="span12" style="text-align:center">
        <iframe class="youtube-player" type="text/html" width="640" height="385" src="{{item.link}}" frameborder="0">
        </iframe>
    </div>
</div>
{% endblock %}


{% block additional_content %}

{% if item.projects.count %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            Used
        </div>
    </div>        
    <div class="span6">
        <div class="detail-item">
            {% for project in item.projects.all %}
            <div id="photo">                    
                <a href="/projects/{{project.title}}/?lightbox={{request.GET.lightbox}}">
                <div id="picture">
                    <div id="info">
                        <div id="holder">
                          <div id="note_count">
                              {{project.title}}
                          </div>
                          <div id="month">
                              {{project.short}}
                          </div>
                       </div>
                   </div>
                   <img src="/static/projects/{{project.title}}/thumbnail.png">
                </div>
                </a>
            </div>            
            {% endfor %}
        </div>
    </div>    
</div>
{% endif %}

{% endblock %}

templates/project_details.html
{% extends 'base_details.html' %}

{% block video %}

{% if item.video_set %}
<div class="row-fluid">
    <div class="span12" style="text-align:center">
            {% for video in item.video_set.all %}
            <iframe class="youtube-player" type="text/html" width="640" height="385" src="{{video.link}}" frameborder="0">
            </iframe>
            {% endfor %}
    </div>
</div>
{% endif %}

{% endblock %}


{% block additional_content %}

{% if item.performances.count %}
<div class="row-fluid">
    <div class="span4">
        <div class="detail-heading">
            Used In
        </div>
    </div>    
    
    <div class="span6">
        <div class="detail-item">
            {% for performance in item.performances.all %}
                <div id="photo">                    
                    <a href="/performances/{{performance.title}}/?lightbox={{request.GET.lightbox}}">
                    <div id="picture">
                        <div id="info">
                            <div id="holder">
                              <div id="note_count">
                                  {{performance.title}}
                              </div>
                              <div id="month">
                                  {{performance.short}}
                              </div>
                           </div>
                       </div>
                       <img src="/static/performances/{{performance.title}}/thumbnail.png">
                    </div>
                    </a>
                </div>            
            {% endfor %}
        </div>
    </div>    
</div>
{% endif %}
{% endblock %}

templates/resume.html
{% extends 'base.html' %}
{% block title %}Resume{% endblock %}

{% block content %}
Content goes here
{% endblock %}